sudo: required
language: node_js
node_js:
      - "8.14"
services:
  - docker

env:
  - DOCKER_IMAGE_NAME=webitel/kibana

before_install:
  - git clone https://github.com/elastic/kibana.git
  - cp disable_enterprise_plugins.patch kibana/
  - cd kibana && git checkout v6.5.4 && git apply disable_enterprise_plugins.patch
  - yarn install --network-timeout 1000000000
  - yarn kbn bootstrap
  - node scripts/build --skip-os-packages --skip-archives --no-oss --release
  - cp -rv ../webitel build/default/kibana-6.5.4-linux-x86_64/plugins && cd build/default/kibana-6.5.4-linux-x86_64/plugins/webitel && yarn install && cd ../../../../../../

install:
  - docker login --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD
  - docker build -t $DOCKER_IMAGE_NAME:6.5.4 .

script:
  - docker push $DOCKER_IMAGE_NAME:6.5.4
