sudo: required
language: node_js
node_js:
      - "8.14.0"
services:
  - docker

env:
  - DOCKER_IMAGE_NAME=webitel/kibana

before_install:
  - git clone https://github.com/elastic/kibana.git
  - cp disable_enterprise_plugins.patch kibana/
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
  - export PATH="$HOME/.yarn/bin:$PATH"
  - cd kibana && git checkout v6.5.4 && git apply disable_enterprise_plugins.patch
  - yarn kbn bootstrap
  - node scripts/build --skip-os-packages --skip-archives --no-oss --release
  - cd ..

install:
  - cp -r webitel kibana/build/default/kibana-6.5.4-linux-x86_64/plugins
  - cd kibana/build/default/kibana-6.5.4-linux-x86_64/plugins/webitel
  - yarn install
  - cd ~/build/webitel/kibana
  - docker login --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD
  - docker build -t $DOCKER_IMAGE_NAME:6.5.4 .

script:
  - docker push $DOCKER_IMAGE_NAME:6.5.4
